// Auto-generated by CompanyCam SDK generator. Do not edit manually.

// Schemas

/**
 * Representation of the company.
 */
export interface Company {
  id: string;
  name: string;
  status?: "active" | "cancelled" | "deleted";
  address?: Address;
  logo?: Array<ImageURI>;
}

/**
 * Representation of the user.
 */
export interface User {
  id: string;
  company_id?: string;
  email_address?: string;
  status?: "active" | "deleted";
  first_name?: string;
  last_name?: string;
  profile_image?: Array<ImageURI>;
  phone_number?: string | null;
  created_at?: number;
  updated_at?: number;
  user_url?: string;
}

/**
 * Representation of the project.
 */
export interface Project {
  id: string;
  company_id?: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  status?: "active" | "deleted";
  archived?: boolean;
  name?: string | null;
  address?: Address;
  coordinates?: Coordinate;
  featured_image?: Array<ImageURI>;
  project_url?: string;
  embedded_project_url?: string;
  integrations?: Array<ProjectIntegration>;
  slug?: string;
  public?: boolean;
  geofence?: Array<Coordinate>;
  primary_contact?: ProjectContactResponse;
  notepad?: string;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the photo.
 */
export interface Photo {
  id: string;
  company_id?: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  project_id?: string;
  processing_status?:
    | "pending"
    | "processing"
    | "processed"
    | "processing_error"
    | "duplicate";
  coordinates?: Array<Coordinate>;
  uris?: Array<ImageURI>;
  hash?: string;
  description?: string;
  internal?: boolean;
  photo_url?: string;
  captured_at?: number;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the tag.
 */
export interface Tag {
  id: string;
  company_id?: string;
  display_value?: string;
  value?: string;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the group.
 */
export interface Group {
  id: string;
  company_id?: string;
  name?: string;
  users?: Array<User>;
  status?: "active" | "deleted";
  group_url?: string;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the webhook.
 */
export interface Webhook {
  id: string;
  company_id?: string;
  url?: string;
  scopes?: Array<string>;
  token?: string;
  enabled?: boolean;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the image uri.
 */
export interface ImageURI {
  type: string;
  uri: string;
  url?: string;
}

/**
 * Representation of the address.
 */
export interface Address {
  street_address_1?: string | null;
  street_address_2?: string | null;
  city?: string | null;
  state?: string | null;
  postal_code?: string | null;
  country?: string | null;
}

/**
 * Standard pagination parameters used across list endpoints.
 */
export interface PaginationQueryParams {
  page?: number;
  per_page?: number;
}

/**
 * Optional header for impersonating a specific CompanyCam user when performing requests.
 */
export interface UserContextHeaderParams {
  /**
   * Email of CompanyCam user to be designated as the actor for the request.
   */
  "X-CompanyCam-User"?: string;
}

/**
 * Representation of the checklist.
 */
export interface Checklist {
  id?: string;
  company_id?: string;
  project_id?: string;
  name?: string;
  created_at?: number;
  updated_at?: number;
  completed_at?: number | null;
  creator_id?: string;
  checklist_template_id?: string | null;
  is_populating?: boolean;
  sectionless_tasks?: Array<Task>;
  sections?: Array<ChecklistSection>;
}

/**
 * Representation of the checklist section.
 */
export interface ChecklistSection {
  id?: string;
  todo_list_id?: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  title?: string;
  position?: number;
  tasks?: Array<Task>;
}

/**
 * Representation of the task.
 */
export interface Task {
  id?: string;
  completed_at?: number;
  completed_by_id?: string;
  completed_by_type?: string;
  created_at?: number;
  creator_id?: string;
  creator_type?: string;
  details?: string;
  photo_capture_required?: boolean;
  position?: number;
  todo_list_id?: string;
  todo_list_section_id?: string | null;
  title?: string;
  updated_at?: number;
  sub_tasks?: Array<SubTask>;
  photos?: Array<Photo>;
}

/**
 * Representation of the sub task.
 */
export interface SubTask {
  id?: string;
  label?: string;
  answer_type?: "open_text" | "multiple_choice" | "yes_no";
  answer_choices?: Array<unknown>;
  answer_options?: Array<string>;
  position?: number;
  task_id?: string;
  answer_text?: string;
}

/**
 * Representation of the checklist template.
 */
export interface ChecklistTemplate {
  id?: string;
  company_id?: string;
  name?: string;
  description?: string;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the coordinate.
 */
export interface Coordinate {
  lat: number;
  lon: number;
}

/**
 * Representation of the project integration.
 */
export interface ProjectIntegration {
  type: string;
  relation_id: string;
}

/**
 * Representation of the comment.
 */
export interface Comment {
  id: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  commentable_id?: string;
  commentable_type?: string;
  status?: string;
  content?: string;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the document.
 */
export interface Document {
  id: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  project_id?: string;
  name?: string;
  url?: string;
  content_type?: string;
  byte_size?: number;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the project contact response.
 */
export interface ProjectContactResponse {
  id?: string;
  project_id?: string;
  name?: string;
  email?: string;
  phone_number?: string;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the error.
 */
export interface Error {
  errors?: Array<string>;
}

/**
 * Representation of the project contact request.
 */
export interface ProjectContactRequest {
  name: string;
  email?: string;
  phone_number?: string;
}

/**
 * Representation of the project notepad.
 */
export interface ProjectNotepad {
  notepad: string;
}

/**
 * Representation of the project collaborator.
 */
export interface ProjectCollaborator {
  id?: string;
  company_id?: string;
  project_id?: string;
  project_invitation_id?: string;
  accepted_at?: number;
  created_at?: number;
  updated_at?: number;
}

/**
 * Representation of the project invitation.
 */
export interface ProjectInvitation {
  id?: string;
  project_id?: string;
  invite_url?: string;
  status?: "accepted" | "expired" | "pending";
  accepted_at?: number;
  accepted_by_id?: string;
  expires_at?: number;
  creator_id?: string;
  created_at?: number;
  updated_at?: number;
}

// Operations

/**
 * Query parameters accepted by the list checklists q operation.
 */
export interface ListChecklistsQueryParams extends PaginationQueryParams {
  completed?: boolean;
}

/**
 * Attributes accepted when creating a user.
 */
export interface UserCreateInput
  extends Pick<
    Partial<User>,
    "first_name" | "last_name" | "email_address" | "phone_number"
  > {
  password?: string;
  user_role?: string;
}

/**
 * Attributes accepted when updating a user.
 */
export interface UserUpdateInput
  extends Pick<
    Partial<User>,
    "first_name" | "last_name" | "email_address" | "phone_number"
  > {
  password?: string;
}

/**
 * Query parameters accepted by the list projects q operation.
 */
export interface ListProjectsQueryParams extends PaginationQueryParams {
  query?: string;
  modified_since?: string;
}

/**
 * Attributes accepted when creating a project.
 */
export interface ProjectCreateInput {
  name?: Project["name"];
  address?: Address;
  coordinates?: Coordinate;
  geofence?: Coordinate[];
  primary_contact?: ProjectContactRequest;
}

/**
 * Attributes accepted when updating a project.
 */
export interface ProjectUpdateInput {
  name?: Project["name"];
  address?: Address;
  coordinates?: Coordinate;
  geofence?: Coordinate[];
}

/**
 * Query parameters accepted by the list project photos q operation.
 */
export interface ListProjectPhotosQueryParams extends PaginationQueryParams {
  start_date?: string;
  end_date?: string;
  user_ids?: Array<number>;
  group_ids?: Array<number>;
  tag_ids?: Array<number>;
}

/**
 * Shape of the photo payload accepted when uploading a project photo.
 */
export interface ProjectPhotoUpload {
  coordinates?: Coordinate;
  uri: string;
  captured_at: number;
  description?: Photo["description"];
  tags?: string[];
}

/**
 * Attributes accepted when uploading a project document.
 */
export interface ProjectDocumentUpload
  extends Pick<Partial<Document>, "name"> {
  attachment?: string;
}

/**
 * Query parameters accepted by the list photos q operation.
 */
export interface ListPhotosQueryParams extends PaginationQueryParams {
  start_date?: string;
  end_date?: string;
  user_ids?: Array<number>;
  group_ids?: Array<number>;
  tag_ids?: Array<number>;
}

/**
 * Attributes accepted when creating or updating a webhook registration.
 */
export interface WebhookMutationInput
  extends Pick<Partial<Webhook>, "url" | "scopes" | "enabled" | "token"> {}
