// Auto-generated by CompanyCam SDK generator. Do not edit manually.

// Schemas

export interface Company {
  id: string;
  name: string;
  status?: "active" | "cancelled" | "deleted";
  address?: Address;
  logo?: Array<ImageURI>;
}

export interface User {
  id: string;
  company_id?: string;
  email_address?: string;
  status?: "active" | "deleted";
  first_name?: string;
  last_name?: string;
  profile_image?: Array<ImageURI>;
  phone_number?: string | null;
  created_at?: number;
  updated_at?: number;
  user_url?: string;
}

export interface Project {
  id: string;
  company_id?: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  status?: "active" | "deleted";
  archived?: boolean;
  name?: string | null;
  address?: Address;
  coordinates?: Coordinate;
  featured_image?: Array<ImageURI>;
  project_url?: string;
  embedded_project_url?: string;
  integrations?: Array<ProjectIntegration>;
  slug?: string;
  public?: boolean;
  geofence?: Array<Coordinate>;
  primary_contact?: ProjectContactResponse;
  notepad?: string;
  created_at?: number;
  updated_at?: number;
}

export interface Photo {
  id: string;
  company_id?: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  project_id?: string;
  processing_status?:
    | "pending"
    | "processing"
    | "processed"
    | "processing_error"
    | "duplicate";
  coordinates?: Array<Coordinate>;
  uris?: Array<ImageURI>;
  hash?: string;
  description?: string;
  internal?: boolean;
  photo_url?: string;
  captured_at?: number;
  created_at?: number;
  updated_at?: number;
}

export interface Tag {
  id: string;
  company_id?: string;
  display_value?: string;
  value?: string;
  created_at?: number;
  updated_at?: number;
}

export interface Group {
  id: string;
  company_id?: string;
  name?: string;
  users?: Array<User>;
  status?: "active" | "deleted";
  group_url?: string;
  created_at?: number;
  updated_at?: number;
}

export interface Webhook {
  id: string;
  company_id?: string;
  url?: string;
  scopes?: Array<string>;
  token?: string;
  enabled?: boolean;
  created_at?: number;
  updated_at?: number;
}

export interface ImageURI {
  type: string;
  uri: string;
  url?: string;
}

export interface Address {
  street_address_1?: string | null;
  street_address_2?: string | null;
  city?: string | null;
  state?: string | null;
  postal_code?: string | null;
  country?: string | null;
}

export interface PaginationQueryParams {
  page?: number;
  per_page?: number;
}

export interface UserContextHeaderParams {
  /**
   * Email of CompanyCam user to be designated as the actor for the request.
   */
  "X-CompanyCam-User"?: string;
}

export interface Checklist {
  id?: string;
  company_id?: string;
  project_id?: string;
  name?: string;
  created_at?: number;
  updated_at?: number;
  completed_at?: number | null;
  creator_id?: string;
  checklist_template_id?: string | null;
  is_populating?: boolean;
  sectionless_tasks?: Array<Task>;
  sections?: Array<ChecklistSection>;
}

export interface ChecklistSection {
  id?: string;
  todo_list_id?: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  title?: string;
  position?: number;
  tasks?: Array<Task>;
}

export interface Task {
  id?: string;
  completed_at?: number;
  completed_by_id?: string;
  completed_by_type?: string;
  created_at?: number;
  creator_id?: string;
  creator_type?: string;
  details?: string;
  photo_capture_required?: boolean;
  position?: number;
  todo_list_id?: string;
  todo_list_section_id?: string | null;
  title?: string;
  updated_at?: number;
  sub_tasks?: Array<SubTask>;
  photos?: Array<Photo>;
}

export interface SubTask {
  id?: string;
  label?: string;
  answer_type?: "open_text" | "multiple_choice" | "yes_no";
  answer_choices?: Array<unknown>;
  answer_options?: Array<string>;
  position?: number;
  task_id?: string;
  answer_text?: string;
}

export interface ChecklistTemplate {
  id?: string;
  company_id?: string;
  name?: string;
  description?: string;
  created_at?: number;
  updated_at?: number;
}

export interface Coordinate {
  lat: number;
  lon: number;
}

export interface ProjectIntegration {
  type: string;
  relation_id: string;
}

export interface Comment {
  id: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  commentable_id?: string;
  commentable_type?: string;
  status?: string;
  content?: string;
  created_at?: number;
  updated_at?: number;
}

export interface Document {
  id: string;
  creator_id?: string;
  creator_type?: string;
  creator_name?: string;
  project_id?: string;
  name?: string;
  url?: string;
  content_type?: string;
  byte_size?: number;
  created_at?: number;
  updated_at?: number;
}

export interface ProjectContactResponse {
  id?: string;
  project_id?: string;
  name?: string;
  email?: string;
  phone_number?: string;
  created_at?: number;
  updated_at?: number;
}

export interface Error {
  errors?: Array<string>;
}

export interface ProjectContactRequest {
  name: string;
  email?: string;
  phone_number?: string;
}

export interface ProjectNotepad {
  notepad: string;
}

export interface ProjectCollaborator {
  id?: string;
  company_id?: string;
  project_id?: string;
  project_invitation_id?: string;
  accepted_at?: number;
  created_at?: number;
  updated_at?: number;
}

export interface ProjectInvitation {
  id?: string;
  project_id?: string;
  invite_url?: string;
  status?: "accepted" | "expired" | "pending";
  accepted_at?: number;
  accepted_by_id?: string;
  expires_at?: number;
  creator_id?: string;
  created_at?: number;
  updated_at?: number;
}

// Operations

export interface ListChecklistsQueryParams extends PaginationQueryParams {
  completed?: boolean;
}

export interface CreateUserRequestBody {
  user?: {
    first_name?: string;
    last_name?: string;
    email_address?: string;
    phone_number?: string;
    password?: string;
    user_role?: string;
  };
}

export interface UpdateUserRequestBody {
  first_name?: string;
  last_name?: string;
  email_address?: string;
  phone_number?: string;
  password?: string;
}

export interface ListProjectsQueryParams extends PaginationQueryParams {
  query?: string;
  modified_since?: string;
}

export interface CreateProjectRequestBody {
  name?: string;
  address?: Address;
  coordinates?: Coordinate;
  geofence?: Array<Coordinate>;
  primary_contact?: ProjectContactRequest;
}

export interface UpdateProjectRequestBody {
  name?: string;
  address?: Address;
  coordinates?: Coordinate;
  geofence?: Array<Coordinate>;
}

export interface ListProjectPhotosQueryParams extends PaginationQueryParams {
  start_date?: string;
  end_date?: string;
  user_ids?: Array<number>;
  group_ids?: Array<number>;
  tag_ids?: Array<number>;
}

export interface CreateProjectPhotoRequestBody {
  photo: {
    coordinates?: Coordinate;
    uri: string;
    captured_at: number;
    description?: string;
    tags?: Array<string>;
  };
}

export interface UpdateProjectNotepadRequestBody {
  notepad: string;
}

export interface CreateProjectLabelsRequestBody {
  project?: {
    labels?: Array<string>;
  };
}

export interface CreateProjectDocumentRequestBody {
  document?: {
    name?: string;
    attachment?: string;
  };
}

export interface CreateProjectCommentRequestBody {
  comment?: {
    content?: string;
  };
}

export interface CreateProjectChecklistRequestBody {
  checklist_template_id?: string;
}

export interface ListPhotosQueryParams extends PaginationQueryParams {
  start_date?: string;
  end_date?: string;
  user_ids?: Array<number>;
  group_ids?: Array<number>;
  tag_ids?: Array<number>;
}

export interface UpdatePhotoRequestBody {
  photo?: {
    internal?: boolean;
  };
}

export interface CreatePhotoTagsRequestBody {
  tags?: Array<string>;
}

export interface CreatePhotoCommentRequestBody {
  comment?: {
    content?: string;
  };
}

export interface UpdatePhotoDescriptionRequestBody {
  description?: string;
}

export interface CreateTagRequestBody {
  tag?: {
    display_value?: string;
  };
}

export interface UpdateTagRequestBody {
  tag?: {
    display_value?: string;
  };
}

export interface CreateGroupRequestBody {
  group?: {
    name?: string;
    users?: Array<string>;
  };
}

export interface UpdateGroupRequestBody {
  group?: {
    name?: string;
    users?: Array<string>;
  };
}

export interface CreateWebhookRequestBody {
  url?: string;
  scopes?: Array<string>;
  enabled?: boolean;
  token?: string;
}

export interface UpdateWebhookRequestBody {
  url?: string;
  scopes?: Array<string>;
  enabled?: boolean;
  token?: string;
}
